# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

# tags: "spring_tag" should match with the tag name provided to runner, for spring runner should execute in shell.
maven-build:
  stage: mavenbuild
  tags:
    - spring_tag
  script:
    - cd /usr/lib/systemd/system/builds/19beb01f/0/CS309SPRING2019/team_40/Backend/spring-fridgetracker
    - mvn package -B
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  tags:
    - spring_tag
  script:
    - cd /usr/lib/systemd/system/builds/19beb01f/0/CS309SPRING2019/team_40/Backend/spring-fridgetracker
    - mvn test
  artifacts:
    paths:
      - /usr/lib/systemd/system/builds/19beb01f/0/CS309SPRING2019/team_40/Backend/spring-fridgetracker/target/*.jar
# autoDeploy
autoDeploy:
  stage: autodeploy
  tags:
   - spring_tag
  script:
    - cd Backend/spring-fridgetracker
    - mvn package
    - sudo mv /usr/lib/systemd/system/builds/19beb01f/0/CS309SPRING2019/team_40/Backend/spring-fridgetracker/target/spring-fridgetracker-0.0.1-SNAPSHOT.jar /target/spring-fridgetracker-0.0.1-SNAPSHOT.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

    
# To build android projects

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./fridge_tracker/gradlew
  tags:
   - android_tag
  script:
    - pwd
    - cd fridge_tracker
    - ./gradlew assemble --stacktrace
  artifacts:
    paths:
    - /fridge_tracker/app/build/outputs/
    
# To run Android unit tests.   
unitTests:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./fridge_tracker/gradlew
  tags:
   - android_tag
  script:
    - cd fridge_tracker
    - ./gradlew test